// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxoILvR9G7m0Hbviqf6cHaG4IuiFz_7qY',
    appId: '1:1073301126008:web:c6f62baa41921d0c94a68d',
    messagingSenderId: '1073301126008',
    projectId: 'project-heretothere',
    authDomain: 'project-heretothere.firebaseapp.com',
    storageBucket: 'project-heretothere.firebasestorage.app',
    measurementId: 'G-3QZB80Z8VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw9pzrva09AfdDW7kcQbWlQDJwl_o3XAU',
    appId: '1:1073301126008:android:7a9d9d6bdec5947694a68d',
    messagingSenderId: '1073301126008',
    projectId: 'project-heretothere',
    storageBucket: 'project-heretothere.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbY0iz-zX1rWJsC7TjiiMgzgnVb7UT9tk',
    appId: '1:1073301126008:ios:e7033ccd6ccfcb0194a68d',
    messagingSenderId: '1073301126008',
    projectId: 'project-heretothere',
    storageBucket: 'project-heretothere.firebasestorage.app',
    iosBundleId: 'com.example.here2thereKids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbY0iz-zX1rWJsC7TjiiMgzgnVb7UT9tk',
    appId: '1:1073301126008:ios:e7033ccd6ccfcb0194a68d',
    messagingSenderId: '1073301126008',
    projectId: 'project-heretothere',
    storageBucket: 'project-heretothere.firebasestorage.app',
    iosBundleId: 'com.example.here2thereKids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxoILvR9G7m0Hbviqf6cHaG4IuiFz_7qY',
    appId: '1:1073301126008:web:2541a53a995a41d494a68d',
    messagingSenderId: '1073301126008',
    projectId: 'project-heretothere',
    authDomain: 'project-heretothere.firebaseapp.com',
    storageBucket: 'project-heretothere.firebasestorage.app',
    measurementId: 'G-00GHEMTEG2',
  );
}
